version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/London"
      time: "04:00"
    labels:
      - "PR • MAINTENANCE"
    assignees:
      - "andyone"
    reviewers:
      - "andyone"
